id: A4A5EE452
base_file: f4504.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 06:45:48.584416
  last_modified_at: 2022-05-31 06:45:48.584443
